### ISSUE TITLE
Prevent device standby

### ISSUE THREAD

**Issue by Lightdasher360** [jflores82/simchecklists#22]
Just another enhancement idea! I thought it would be nice if the web app page could prevent mobile devices from sleeping while it's active, or if there could be an option to toggle such a function.

I can personally just set my tablet to never auto sleep, but noticed an old smartphone I have doesn't allow this, and figured such an option could be helpful to users with this case.

**Comment by jflores82** [comment]
appied a test fix for this in v1.1.5: https://github.com/jflores82/simchecklists/commit/9393c773468febe51dba76ce126d1869af9ad2b9

tested on my android phone in chrome and adblock, seems to work ok, as long as you access the live site via https (wake-lock api is only avaiable through a secure context).

will leave it open, since it still needs more testing, if possible.

**Comment by Lightdasher360** [comment]
Works as well for me! Tested through Android phone via Brave.

**Comment by jflores82** [comment]
Tested on more devices, as of 1.1.6 seems correct, closing issue. 

https://github.com/jflores82/simchecklists/commit/5fe7fa36039a60dbbd2acd925fbb617f8b5716ae
