### ISSUE TITLE
Scratchpad gets cut off when changing screen orientation

### ISSUE THREAD

**Issue by Lightdasher360** [jflores82/simchecklists#30]
https://github.com/jflores82/simchecklists/assets/172877039/76916a3b-89c6-494d-9dce-1cc3b65cf8d6

https://github.com/jflores82/simchecklists/assets/172877039/3d71ee1d-baae-4d1b-9d7d-e17fc5a1c268

Hope the clips show well! I'm not sure how best to describe this otherwise..

**Comment by jflores82** [comment]
pushed a test fix for this in v1.1.6: https://github.com/jflores82/simchecklists/commit/5fe7fa36039a60dbbd2acd925fbb617f8b5716ae 

since i don't rescale the canvas, the drawn parts that are offscreen are lost when changing orientation, due to that, i'm not closing this issue just yet, while i search for a better option, but the whole canvas seems to be usable now, regardless of orientation and change. 
i can also code it to clear the canvas on orientation change, if that is a better suited solution, please let me know.

**Comment by Lightdasher360** [comment]
I think the current fix is the best one for now, thank you!

**Comment by jflores82** [comment]
Issue closed as ver v1.1.8 - if required, will be reopened.
